version: "3"

volumes:
    mongodb_data_db:

services:
    gathio:
        build: .
        links:
            - mongo
        ports:
            - 3000:3000
        volumes:
            # The path to Gathio's config folder - change to match your system
            - ./gathio-docker/config:/app/config
            # The path to Gathio's user-uploaded event images folder - change to match your system
            - ./gathio-docker/events:/app/public/events
    mongo:
        image: mongo:latest
        volumes:
            - mongodb_data_db:/data/db
